export const AllLinks = [
  {
    name: "Informaion",
    linkName: "informationLinks",
    links: [
      { name: "About Us", link: "/about" },
      { name: "About Zip", link: "/about" },
      { name: "Privacy Policy", link: "/about" },
      { name: "Search", link: "/about" },
      { name: "Terms", link: "/about" },
      { name: "Order and Returns", link: "/about" },
      { name: "Contact Us", link: "/about" },
      { name: "Advanced Search", link: "/about" },
      { name: "Newsletter Subscription", link: "/about" },
    ],
  },
  {
    name: "PC Parts",
    linkName: "pcPartsLinks",
    links: [
      { name: "CPUS", link: "/about" },
      { name: "Add on Cards", link: "/about" },
      { name: "Hard Drives(internal)", link: "/about" },
      { name: "Grapich Cards", link: "/about" },
      { name: "Keyboard / Mice", link: "/about" },
      { name: "Cases / Power Supplies / Cooling", link: "/about" },
      { name: "RAM (Memory)", link: "/about" },
      { name: "Software", link: "/about" },
      { name: "Speakers / Headsets", link: "/about" },
      { name: "Motherboards", link: "/about" },
    ],
  },
  {
    name: "Desktop PCs",
    linkName: "desktopPcLinks",
    links: [
      { name: "Custom PCs", link: "/about" },
      { name: "Servers", link: "/about" },
      { name: "MSI All-in-One PCs", link: "/about" },
      { name: "HP/Compaq PCs", link: "/about" },
      { name: "ASUS PCs", link: "/about" },
      { name: "Tecs PCs", link: "/about" },
    ],
  },
  {
    name: "Laptops",
    linkName: "laptopsLinks",
    links: [
      { name: "Everysay Use Notebook", link: "/about" },
      { name: "MSI Workstation Series", link: "/about" },
      { name: "MSI Prestige Series", link: "/about" },
      { name: "Tablets and Pads", link: "/about" },
      { name: "Netbooks", link: "/about" },
      { name: "Infinity Gaming Notbooks", link: "/about" },
    ],
  },
  {
    name: "Address",
    linkName: "address",
    links: [
      { name: "Address : 1234 Street Adress City Address, 1234" },
      { name: "Phones: (00) 1234 5678", link: "/about" },
      { name: "We are open: Monday-Thursday: 9:00 AM - 5:30 PM" },
      { name: "Friday: 9:00 AM - 6:00 PM" },
      { name: "Saturday: 11:00 AM - 5:00 PM" },
      { name: "E-mail: shop@email.com", link: "/about" },
    ],
  },
];
